version: "3.8"

services:

  mongo:
    image: mongo:6
    container_name: cine-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - cine-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.runCommand({ ping: 1 })"]
      interval: 10s
      timeout: 5s
      retries: 5
   

  backend:
    build:
      context: ./
    container_name: cine-backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env.docker
    depends_on:
      mongo:
        condition: service_healthy
    volumes:
      - ./uploads:/app/uploads
    networks:
      - cine-network

  frontend:
    build:
      context: ./frontend
    container_name: cine-frontend
    restart: unless-stopped
    ports:
      - "5173:80"
    depends_on:
      - backend
    networks:
      - cine-network

networks:
  cine-network:
    driver: bridge

volumes:
  mongo_data: 