events {}

http {
  # Redirect HTTP → HTTPS
  server {
    listen 80;
    server_name cinepulse.duckdns.org;
    return 301 https://$host$request_uri;
  }

  server {
    listen 443 ssl;
    server_name cinepulse.duckdns.org;

    ssl_certificate     /etc/letsencrypt/live/cinepulse.duckdns.org/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/cinepulse.duckdns.org/privkey.pem;

    client_max_body_size 50M;

    # Backend API
    location / {
      proxy_pass http://backend:3000;
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection 'upgrade';
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
      proxy_cache_bypass $http_upgrade;
    }

    # Grafana — protected by basic auth
    location /grafana/ {
      auth_basic "Monitoring";
      auth_basic_user_file /etc/nginx/.htpasswd;

      proxy_pass http://grafana:3000/;
      proxy_http_version 1.1;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
      proxy_set_header X-Forwarded-Proto $scheme;   # ← add this
    }
  }
}