name: Backend CI/CD

on:
  push:
    branches:
      - main                    # deploy only on main
    paths:
      - "backend/**"
      - "docker-compose.yml"
      - "Dockerfile"
      - "package.json"
  pull_request:
    branches:
      - main                    # just validate on PR, no deploy
    paths:
      - "backend/**"
      - "docker-compose.yml"
      - "Dockerfile"
      - "package.json"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy Backend to EC2
        if: github.event_name == 'push'       # 👈 deploy only on actual push to main, not PR
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/CinePulse

            echo "Pulling latest code..."
            git pull origin main

            echo "Rebuilding backend container only..."
            docker compose up -d --build backend

            echo "Cleaning unused docker images..."
            docker image prune -f

            echo "Deployment completed successfully!"