name: Frontend CI/CD

on:
  push:
    branches: ['*']
  pull_request:
    branches: [main]

jobs:
  build-deploy:
    runs-on: utubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json

      - name: Install frontend dependencies
        working-directory: frontend
        run: npm ci
      
      - name: Build React app
        working-directory: frontend
        run: npm run build
      
      - name: Print success message
        run: echo "Frontend build completed successfully!"